{% macro county_to_region(county_col) %}
case
  when {{ county_col }} = 'GREATER LONDON' then 'London'
  when {{ county_col }} in (
    'SURREY','KENT','EAST SUSSEX','WEST SUSSEX','HAMPSHIRE','BERKSHIRE',
    'BUCKINGHAMSHIRE','OXFORDSHIRE','HERTFORDSHIRE','ESSEX',
    'BRACKNELL FOREST','ISLE OF WIGHT','MEDWAY','MILTON KEYNES',
    'READING','SLOUGH','SOUTHEND-ON-SEA','THURROCK','PORTSMOUTH',
    'SOUTHAMPTON','BRIGHTON AND HOVE','WEST BERKSHIRE',
    'WINDSOR AND MAIDENHEAD','WOKINGHAM'
  ) then 'South East'
  when {{ county_col }} in (
    'NORFOLK','SUFFOLK','CAMBRIDGESHIRE','BEDFORD',
    'CENTRAL BEDFORDSHIRE','LUTON','CITY OF PETERBOROUGH'
  ) then 'East of England'
  when {{ county_col }} in (
    'DEVON','CORNWALL','DORSET','SOMERSET','WILTSHIRE','GLOUCESTERSHIRE',
    'BATH AND NORTH EAST SOMERSET','CITY OF BRISTOL','NORTH SOMERSET',
    'SOUTH GLOUCESTERSHIRE','CITY OF PLYMOUTH','ISLES OF SCILLY',
    'SWINDON','TORBAY','BOURNEMOUTH, CHRISTCHURCH AND POOLE'
  ) then 'South West'
  when {{ county_col }} in (
    'DERBYSHIRE','LEICESTERSHIRE','LINCOLNSHIRE','NORTHAMPTONSHIRE',
    'NOTTINGHAMSHIRE','RUTLAND','CITY OF DERBY','LEICESTER',
    'CITY OF NOTTINGHAM','NORTH EAST LINCOLNSHIRE','NORTH LINCOLNSHIRE',
    'NORTH NORTHAMPTONSHIRE','WEST NORTHAMPTONSHIRE'
  ) then 'East Midlands'
  when {{ county_col }} in (
    'STAFFORDSHIRE','WEST MIDLANDS','HEREFORDSHIRE','SHROPSHIRE',
    'WREKIN','STOKE-ON-TRENT','WORCESTERSHIRE','WARWICKSHIRE'
  ) then 'West Midlands'
  when {{ county_col }} in (
    'LANCASHIRE','GREATER MANCHESTER','MERSEYSIDE','CUMBRIA',
    'HALTON','BLACKBURN WITH DARWEN','BLACKPOOL',
    'CHESHIRE EAST','CHESHIRE WEST AND CHESTER','CUMBERLAND',
    'WARRINGTON','WESTMORLAND AND FURNESS'
  ) then 'North West'
  when {{ county_col }} in (
    'TYNE AND WEAR','COUNTY DURHAM','NORTHUMBERLAND',
    'HARTLEPOOL','MIDDLESBROUGH','REDCAR AND CLEVELAND',
    'STOCKTON-ON-TEES','DARLINGTON'
  ) then 'North East'
  when {{ county_col }} in (
    'SOUTH YORKSHIRE','NORTH YORKSHIRE','WEST YORKSHIRE',
    'EAST RIDING OF YORKSHIRE','CITY OF KINGSTON UPON HULL','YORK'
  ) then 'Yorkshire & Humber'
  when {{ county_col }} in (
    'CARDIFF','SWANSEA','NEWPORT','BRIDGEND','CAERPHILLY',
    'CARMARTHENSHIRE','CEREDIGION','CONWY','DENBIGHSHIRE',
    'FLINTSHIRE','GWYNEDD','ISLE OF ANGLESEY','MERTHYR TYDFIL',
    'MONMOUTHSHIRE','NEATH PORT TALBOT','PEMBROKESHIRE','POWYS',
    'RHONDDA CYNON TAFF','THE VALE OF GLAMORGAN','TORFAEN','BLAENAU GWENT',
    'WREXHAM'
  ) then 'Wales'
  else 'Other England'
end
{% endmacro %}
